spring.application.name=app_seguridad
server.port=8081

spring.datasource.url=jdbc:h2:mem:seguridad_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuración de manejo de errores
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=on_param
server.error.include-exception=false
spring.mvc.throw-exception-if-no-handler-found=true

#Configuración de correo electrónico
#Indicar el servidor de correo saliente (SMTP) que se usará
spring.mail.host=smtp.gmail.com
#Indicar el puerto usado por GMAIL
spring.mail.port=587
#Indicar las credenciales del correo que enviará los mensajes
#Remitente
spring.mail.username=pruebasapis8@gmail.com
#Contraseña de aplicación (esto se hace al configurar GMAIL en autenticación en dos pasos)
spring.mail.password=aehaixkapkavzwyt
#Indicar que el servidor SMTP requiere autenticación
spring.mail.properties.mail.smtp.auth=true
#Protocolo que cifra la conexion con el servidor de corre
spring.mail.properties.mail.smtp.starttls.enable=true
# Tamaño máximo de archivo adjunto (ajustable)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
# Opcional (para depurar) ver por consola los detalles de la conexion
logging.level.org.springframework.mail=DEBUG